# -*- coding: utf-8 -*-
"""Scan merged IME word assets; emit char_frequency_weights.txt (Han character → weight).

权重 = 词库中出现次数 + 通用字序加成（减轻成语/天文等专业词条对「单字排序」的偏置）。
可选 assets/char_frequency_general_rank.txt：每行一字，自上而下越常用（若存在则与内置字序合并，文件优先）。
"""
from __future__ import annotations

from collections import Counter
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
ASSETS = ROOT / "app" / "src" / "main" / "assets"
OUT_NAME = "char_frequency_weights.txt"
OPTIONAL_RANK_FILE = ASSETS / "char_frequency_general_rank.txt"

# 与运行时 loadWordList 合并列表一致（含扩展 batch）
FILES = [
    "pinyin_words.txt",
    "car_brands.txt",
    "pinyin_words_poetry.txt",
    "pinyin_words_food.txt",
    "pinyin_words_countries.txt",
    "pinyin_words_modern.txt",
    "pinyin_append_temp.txt",
    "wordlist_idioms.txt",
    "wordlist_astronomy.txt",
    "wordlist_daily.txt",
    "pinyin_words_extended_batch_a.txt",
]

# 内置：现代汉语极高频字串（大致按常用度排列，仅首次出现计入序）。越靠前加成越大。
# 可与 optional 文件叠加：先读内置，再读文件中的字（文件中未出现的字接续编号）。
GENERAL_RANK_EMBEDDED = (
    "的一是在不了有和人这中大为上个国我以要他时来用们生到作地于出就分对成会可主发年动同工也能下过"
    "子说产种面而方后多定行学法所民得经十三之进着等部度家电力里如水化高自二理起小物现实加量都两"
    "体制机当使点从业本去把性好应开它合还因由其些然前外天政四日那社义事平形相全表间样与关各重新线"
    "内数正心反你明看原又么利比或但质气第向道命此变条只没结解问意建月公无系军很情者最立代想已通"
    "并提直题党程展五果料象员革位入常文总次品式活设及管特件长求老头基资边流路级少图山统接知较将"
    "组见计别她手角期根论运农指几九区强放决西被干做必战先回则任取据处队南给色光门即保治北造百规"
    "热领七海口东导器压志世金增争济阶油思术极交受联什认六共权收证改清己美再采转更单风切打白教速"
    "花带安场身车例真务具万每目至达走积示议声报斗完类八离华名确才科张信马节话米整空元况今集温传"
    "土许步群广石记需段研界拉林律叫且究观越织装影算低持音众书布复容儿须际商非验连断深难近矿千周"
    "委素技备半办青省列习响约支般史感劳便团往酸历市克何除消构府称太准精值号率族维划选标写存候毛"
    "亲快效斯院查江型眼王按格养易置派层片始却专状育厂京识适属圆包火住调满县局照参红细引听该铁价"
    "严龙飞背景背被倍杯悲碑卑贝辈惫焙狈钡本苯笨绷泵蹦迸逼鼻比鄙笔彼碧蔽毕毙币庇痹闭敝弊必辟壁避"
    "陛鞭边编贬扁便变卞辨辩辫遍标彪膘表鳖憋别瘪彬斌滨宾兵冰柄丙秉饼炳病并玻菠播拨钵波博勃脖膊渤"
    "驳捕卜哺补埠步簿怖擦猜裁材才财踩采彩菜蔡餐参蚕残惭惨灿苍舱仓沧藏操糙槽曹草厕策侧册测层蹭插"
    "叉茬茶察岔差诧拆柴馋缠铲产昌猖场尝常长偿肠敞畅唱抄钞朝潮巢吵炒扯撤澈郴臣辰尘晨忱沉陈趁衬撑"
    "称城橙成呈乘程惩澄诚承逞骋秤吃痴持匙池迟弛驰耻齿侈尺赤翅斥炽充冲虫崇宠抽酬畴踌稠愁筹绸瞅丑"
    "臭初出橱厨躇锄雏滁除楚础矗搐触处揣川穿椽传船喘串疮窗幢床闯创吹炊捶锤垂春椿醇唇淳纯蠢戳绰茨"
    "磁雌辞慈瓷词刺赐次聪葱囱匆从丛凑粗醋簇促蹿篡窜摧崔催脆瘁粹淬翠村存寸磋撮搓措挫错搭达答瘩打"
)

# 加成系数：rank 0 的字获得约 (N-1)*SCALE 的额外分；与词库计数同量级可调
BONUS_SCALE = 5


def is_cjk_char(ch: str) -> bool:
    o = ord(ch)
    return (
        0x4E00 <= o <= 0x9FFF
        or 0x3400 <= o <= 0x4DBF
        or 0x20000 <= o <= 0x2CEAF
    )


def parse_line_counts(line: str, counter: Counter[str]) -> None:
    line = line.strip()
    if not line or line.startswith("#"):
        return
    sp = line.find(" ")
    if sp <= 0:
        return
    word = line[sp + 1 :].strip()
    if not word:
        return
    for ch in word:
        if is_cjk_char(ch):
            counter[ch] += 1


def build_rank_order() -> list[str]:
    """返回按常用度递减的字序列表（无重复）。"""
    seen: set[str] = set()
    order: list[str] = []

    def consume(s: str) -> None:
        for ch in s:
            if not is_cjk_char(ch):
                continue
            if ch in seen:
                continue
            seen.add(ch)
            order.append(ch)

    consume(GENERAL_RANK_EMBEDDED)
    if OPTIONAL_RANK_FILE.exists():
        for raw in OPTIONAL_RANK_FILE.read_text(encoding="utf-8").splitlines():
            t = raw.strip()
            if not t or t.startswith("#"):
                continue
            # 支持「一字一行」或「字<TAB>…」
            ch = t[0] if t else ""
            if ch and is_cjk_char(ch):
                consume(ch)
    return order


def main() -> None:
    ctr: Counter[str] = Counter()
    for name in FILES:
        path = ASSETS / name
        if not path.exists():
            continue
        for raw in path.read_text(encoding="utf-8").splitlines():
            parse_line_counts(raw, ctr)

    rank_order = build_rank_order()
    n_ranks = len(rank_order)
    rank_index = {ch: i for i, ch in enumerate(rank_order)}

    final: dict[str, int] = {}
    for ch, c in ctr.items():
        bonus = (n_ranks - 1 - rank_index[ch]) * BONUS_SCALE if ch in rank_index else 0
        final[ch] = c + bonus

    # 仅在通用序中出现、词库未统计到的字：仍写入较低权重，便于极罕用字相对顺序
    for ch in rank_order:
        if ch not in final:
            r = rank_index[ch]
            final[ch] = max(1, (n_ranks - 1 - r) * BONUS_SCALE // 2)

    out_path = ASSETS / OUT_NAME
    lines = [
        "# Auto-generated by scripts/build_char_frequency_from_wordlists.py",
        "# Format: <char>\\t<weight>  (corpus count + general-rank bonus)",
    ]
    for ch, w in sorted(final.items(), key=lambda x: (-x[1], x[0])):
        lines.append(f"{ch}\t{w}")
    out_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Wrote {len(final)} chars to {out_path.relative_to(ROOT)} (rank list length={n_ranks})")


if __name__ == "__main__":
    main()
